spring.application.name=url-shortener

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=postgres
spring.datasource.password=mishalp789

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.data.redis.host=localhost
spring.data.redis.port=6379

management.endpoints.web.exposure.include=*

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG

app.jwt.secret=ReplaceThisWithA256BitSecretKeyForDevelopmentOnlyReplace12345
app.jwt.expiration=86400000


app.base-url=http://localhost:8080