# ---------- DATABASE ----------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ---------- REDIS ----------
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=6000

# ---------- JWT ----------
app.jwt.secret=${JWT_SECRET}

# ---------- LOGGING ----------
logging.level.root=INFO
logging.level.org.springframework.security=WARN
logging.level.com.zaxxer.hikari=INFO

# ---------- ACTUATOR ----------
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.health.redis.enabled=false

server.port=${PORT:8080}
