# -----------------------------------
# Application
# -----------------------------------
spring.application.name=url-shortener
server.port=8080

# -----------------------------------
# PostgreSQL
# -----------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=postgres
spring.datasource.password=mishalp789
spring.datasource.driver-class-name=org.postgresql.Driver

# -----------------------------------
# JPA / Hibernate
# -----------------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# -----------------------------------
# Flyway
# -----------------------------------
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# -----------------------------------
# Redis
# -----------------------------------
spring.data.redis.host=localhost
spring.data.redis.port=6379

# -----------------------------------
# Actuator
# -----------------------------------
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# -----------------------------------
# Logging
# -----------------------------------
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE